# Generated by Django 4.1.7 on 2023-05-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_contact_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(upload_to='service')),
                ('service_img_1', models.ImageField(upload_to='service')),
                ('service_title', models.CharField(max_length=255)),
                ('service_text', models.CharField(max_length=255)),
                ('service_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
    ]
