# Generated by Django 4.1.7 on 2023-05-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_services_delete_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_img', models.ImageField(upload_to='service')),
                ('project_img_1', models.ImageField(upload_to='service')),
                ('project_title', models.CharField(max_length=255)),
                ('project_text', models.CharField(max_length=255)),
                ('project_link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
    ]
